### ISSUE TITLE
needs update to new module-based installation

### ISSUE THREAD

**Issue by aspiers** [paulwellnerbou/git-deps-docker#2]
Hi there,

I will shortly be merging [a PR to package `git-deps` as a Python module](https://github.com/aspiers/git-deps/pull/71).  As a result the installation process has changed slightly, e.g.

- Some files are now in different places.
- The installation workflow is based on Python's popular `setuptools` framework.

It would be great if we could collaborate to get this repo working with the new approach :-)

**Comment by paulwellnerbou** [comment]
@aspiers , sure, I will.
Although I am not sure if this docker project still makes sense (I created it to work around installation problems on ubuntu, which are not there any more, I hope). But it won't hurt, and it is always good to have a working automatic setup.

**Comment by aspiers** [comment]
Thanks!  I think it probably does still make sense, because for several Linux distributions it can be challenging to find the right versions of packages for libgit2 and pygit2 which match.  And in the future it is possible that git-deps might also get more fussy about which versions of pygit2 it works with.

**Comment by paulwellnerbou** [comment]
@aspiers , tried it just now, with python's docker image as base. But `pip install git-deps` is not working yet. It will, when the release is out, right?

**Comment by aspiers** [comment]
It should work now.

**Comment by paulwellnerbou** [comment]
@aspiers , thanks.
On a clean system, the setup still does not work as documented in your README:
(see https://github.com/paulwellnerbou/git-deps-docker/blob/update-for-git-deps-python-module/Dockerfile)

```
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/local/include/python3.6m -c src/blob.c -o build/temp.linux-x86_64-3.6/src/blob.o
    In file included from src/blob.h:34:0,
                     from src/blob.c:30:
    src/types.h:36:2: error: #error You need a compatible libgit2 version (v0.27.x)
     #error You need a compatible libgit2 version (v0.27.x)
      ^
    src/types.h:82:5: error: unknown type name ‘git_worktree’
         git_worktree *worktree;
         ^
    error: command 'gcc' failed with exit status 1
```
Is libgit2 v.0.27.x required?

**Comment by aspiers** [comment]
No, currently only pygit >= 0.24.0 is required but did you follow the link in INSTALL.md to http://www.pygit2.org/install.html#version-numbers ?

**Comment by aspiers** [comment]
i.e. sounds to me like you are trying to install a pygit2 which is too new for your libgit2.

**Comment by paulwellnerbou** [comment]
@aspiers, no, I just tried to follow your steps under https://github.com/aspiers/git-deps/blob/master/INSTALL.md#option-2-install-libgit2-from-os-packages-and-git-deps--pygit2-as-python-modules

I will try another option.

**Comment by aspiers** [comment]
Yeah, by default `pip` will try to install the latest pygit2 if it is not aware of a reason not to.  So I am guessing your `pip` was previously trying to install pygit2 0.27 on top of libgit2 0.24 which is known not to work.  It seems that in #3 you found the perfect workaround which is to specify the desired pygit2 version in the `pip` command:

    pip install pygit2==0.24 git-deps

Therefore I will steal this trick and add it to the docs - thanks a lot!!
